/**
 * @file layout.js
 * @description Layout raíz de la aplicación Next.js (App Router).
 * Define la estructura HTML base que envuelve todas las páginas, incluyendo
 * las fuentes tipográficas y los metadatos globales del sitio.
 */

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

/**
 * Fuente sans-serif principal de la aplicación.
 * Se expone como variable CSS "--font-geist-sans" para uso en estilos.
 */
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

/**
 * Fuente monoespaciada para código y datos técnicos.
 * Se expone como variable CSS "--font-geist-mono".
 */
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

/**
 * Metadatos globales de la aplicación.
 * Next.js usa este objeto para generar las etiquetas <title> y <meta description>
 * en el HTML de cada página.
 */
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * Componente de layout raíz. Envuelve toda la aplicación.
 * Next.js lo aplica automáticamente a todas las rutas del proyecto.
 *
 * @param {Object}    props          - Props del componente.
 * @param {ReactNode} props.children - Contenido de la página activa que se renderiza aquí.
 * @returns {JSX.Element} Estructura HTML base de la aplicación.
 */
export default function RootLayout({ children }) {
  return (
    // Las variables de fuente se añaden como clases en el elemento <html>
    // para que estén disponibles globalmente mediante CSS custom properties
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body>{children}</body>
    </html>
  );
}
